export const ENVIRONMENT_BASE_URL_API_STNHD =
  "ENV_ENVIRONMENT_BASE_URL_API_STNHD"
export const ENVIRONMENT_BASE_URL_API = "ENV_ENVIRONMENT_BASE_URL_API"
export const ENVIRONMENT_BASE_URL_API_FIRE_BASE =
  "ENV_ENVIRONMENT_BASE_URL_API_FIRE_BASE"
export const ENVIRONMENT_FIRE_BASE_SECURITY =
  "ENV_ENVIRONMENT_FIRE_BASE_SECURITY"

//API STATUS
export const ENVIRONMENT_VERSION_DESKTOP = "ENV_ENVIRONMENT_VERSION_DESKTOP"
export const ENVIRONMENT_mainDir = "ENV_ENVIRONMENT_mainDir"
export const ENVIRONMENT_avatarDir = "ENV_ENVIRONMENT_avatarDir"
export const ENVIRONMENT_rootDir = "ENV_ENVIRONMENT_rootDir"
export const ENVIRONMENT_firebaseConfig = "ENV_ENVIRONMENT_firebaseConfig"
export const FACEBOOK_PAGE_ID = ""
