export default [
  {
    id: 'home',
    title: 'Trang chủ',
    titleI18n: 'MENU:home',
    to: '/',
    submenu: [],
  },
  {
    id: 'introduce',
    title: 'Giới thiệu',
    titleI18n: 'MENU:introduce',
    to: '/introduce',
    submenu: [],
  },
  {
    id: 'teachers',
    title: 'Đội ngũ giáo viên',
    titleI18n: 'MENU:teachers',
    to: '/teachers',
    submenu: [],
  },
  {
    id: 'partners',
    title: 'Đối tác',
    titleI18n: 'MENU:partners',
    to: '/partners',
    submenu: [],
  },
  {
    id: 'news',
    title: 'Tin tức',
    titleI18n: 'MENU:news',
    to: '/news',
    submenu: [],
  },
  {
    id: 'support',
    title: 'Hỗ trợ',
    titleI18n: 'MENU:support',
    to: '/support',
    submenu: [],
  },
  {
    id: 'contact',
    title: 'Liên hệ',
    titleI18n: 'MENU:contact',
    to: '/contact',
    submenu: [],
  },
];
